<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZpF16d\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZpF16d/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDZpF16d.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDZpF16d\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDZpF16d\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DZpF16d',
    'container.build_id' => 'f0295dad',
    'container.build_time' => 1617904479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZpF16d');
