<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLZ0cE7p\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLZ0cE7p/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLZ0cE7p.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLZ0cE7p\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLZ0cE7p\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LZ0cE7p',
    'container.build_id' => 'c6246335',
    'container.build_time' => 1620256564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLZ0cE7p');
