<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'categorie_soin_m_p' => [[], ['_controller' => 'App\\Controller\\CategorieSoinMPController::index'], [], [['text', '/categoriesoinmp']], [], []],
    'afficherCategorieSoinMP' => [[], ['_controller' => 'App\\Controller\\CategorieSoinMPController::listCategoriesSoinMP'], [], [['text', '/afficherCategorieSoinMP']], [], []],
    'afficherCategorieSoinMPs' => [[], ['_controller' => 'App\\Controller\\CategorieSoinMPController::listCategoriesSoinMPs'], [], [['text', '/afficherCategorieSoinMPs']], [], []],
    'ajouterCategorieSoinMP' => [[], ['_controller' => 'App\\Controller\\CategorieSoinMPController::ajouterCategorieSoinMP'], [], [['text', '/ajouterCategorieSoinMP']], [], []],
    'supprimerCategorieSoinMP' => [['id'], ['_controller' => 'App\\Controller\\CategorieSoinMPController::SupprimerCategorieSoinMP'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/supprimerCategorieSoinMP']], [], []],
    'modifierCategorieSoinMP' => [['id'], ['_controller' => 'App\\Controller\\CategorieSoinMPController::modifierCategorieSoinMP'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifierCategorieSoinMP']], [], []],
    'postcategorie' => [[], ['_controller' => 'App\\Controller\\PostCategorieController::index'], [], [['text', '/postCategorie']], [], []],
    'afficherCategoriePost' => [[], ['_controller' => 'App\\Controller\\PostCategorieController::afficherCategoriePost'], [], [['text', '/afficherCategoriePost']], [], []],
    'soin_m_p' => [[], ['_controller' => 'App\\Controller\\SoinMPController::index'], [], [['text', '/soin/m/p']], [], []],
    'afficherSoinMP' => [[], ['_controller' => 'App\\Controller\\SoinMPController::listSoinMP'], [], [['text', '/afficherSoinMP']], [], []],
    'afficherSoinMPs' => [['id'], ['_controller' => 'App\\Controller\\SoinMPController::listSoinMPs'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/afficherSoinMPs']], [], []],
    'ajouterSoinMP' => [[], ['_controller' => 'App\\Controller\\SoinMPController::ajouterSoinMP'], [], [['text', '/ajouterSoinMP']], [], []],
    'supprimerSoinMP' => [['id'], ['_controller' => 'App\\Controller\\SoinMPController::SupprimerSoinMP'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/supprimerSoinMP']], [], []],
    'modifierSoinMP' => [['id'], ['_controller' => 'App\\Controller\\SoinMPController::modifierSoinMP'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifierSoinMP']], [], []],
    'upload_test' => [[], ['_controller' => 'App\\Controller\\SoinMPController::temporaryUploadAction'], [], [['text', '/admin/upload/test']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], []],
    'Patients' => [[], ['_controller' => 'App\\Controller\\UserController::ListPatients'], [], [['text', '/Patients']], [], []],
    'Medecins' => [[], ['_controller' => 'App\\Controller\\UserController::ListMedcins'], [], [['text', '/Medecins']], [], []],
    'Pharmaciens' => [[], ['_controller' => 'App\\Controller\\UserController::ListPharmciens'], [], [['text', '/Pharmaciens']], [], []],
];
