<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CentreMedical extends \App\Entity\CentreMedical implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'nomCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'adresseCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'typeCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'numTelCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'mailCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'reservations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'nomCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'adresseCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'typeCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'numTelCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'mailCentreMedical', '' . "\0" . 'App\\Entity\\CentreMedical' . "\0" . 'reservations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CentreMedical $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCentreMedical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCentreMedical', []);

        return parent::getNomCentreMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCentreMedical(string $nomCentreMedical): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCentreMedical', [$nomCentreMedical]);

        return parent::setNomCentreMedical($nomCentreMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseCentreMedical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseCentreMedical', []);

        return parent::getAdresseCentreMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseCentreMedical(string $adresseCentreMedical): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseCentreMedical', [$adresseCentreMedical]);

        return parent::setAdresseCentreMedical($adresseCentreMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeCentreMedical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeCentreMedical', []);

        return parent::getTypeCentreMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeCentreMedical(string $typeCentreMedical): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeCentreMedical', [$typeCentreMedical]);

        return parent::setTypeCentreMedical($typeCentreMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTelCentreMedical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTelCentreMedical', []);

        return parent::getNumTelCentreMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTelCentreMedical(string $numTelCentreMedical): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTelCentreMedical', [$numTelCentreMedical]);

        return parent::setNumTelCentreMedical($numTelCentreMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailCentreMedical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailCentreMedical', []);

        return parent::getMailCentreMedical();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailCentreMedical(?string $mailCentreMedical): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailCentreMedical', [$mailCentreMedical]);

        return parent::setMailCentreMedical($mailCentreMedical);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\App\Entity\Reservation $reservation): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\App\Entity\Reservation $reservation): \App\Entity\CentreMedical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

}
