<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actualite extends \App\Entity\Actualite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'titreArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'sloganArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'textArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'creation', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'enPremier', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'couverture', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'typeArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'medias'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'titreArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'sloganArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'textArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'creation', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'enPremier', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'couverture', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'typeArticle', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Actualite' . "\0" . 'medias'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Actualite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreArticle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreArticle', []);

        return parent::getTitreArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreArticle(string $titreArticle): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreArticle', [$titreArticle]);

        return parent::setTitreArticle($titreArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSloganArticle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSloganArticle', []);

        return parent::getSloganArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSloganArticle(string $sloganArticle): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSloganArticle', [$sloganArticle]);

        return parent::setSloganArticle($sloganArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextArticle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextArticle', []);

        return parent::getTextArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextArticle(string $textArticle): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextArticle', [$textArticle]);

        return parent::setTextArticle($textArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getActif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActif', []);

        return parent::getActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif(?string $actif): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', [$actif]);

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreation', []);

        return parent::getCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreation(\DateTimeInterface $creation): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreation', [$creation]);

        return parent::setCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnPremier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnPremier', []);

        return parent::getEnPremier();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnPremier(string $enPremier): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnPremier', [$enPremier]);

        return parent::setEnPremier($enPremier);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouverture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouverture', []);

        return parent::getCouverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouverture(string $couverture): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouverture', [$couverture]);

        return parent::setCouverture($couverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeArticle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeArticle', []);

        return parent::getTypeArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeArticle(string $typeArticle): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeArticle', [$typeArticle]);

        return parent::setTypeArticle($typeArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', []);

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\App\Entity\Media $media): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', [$media]);

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\App\Entity\Media $media): \App\Entity\Actualite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', [$media]);

        return parent::removeMedia($media);
    }

}
