<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDcoOOkQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDcoOOkQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDcoOOkQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDcoOOkQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDcoOOkQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DcoOOkQ',
    'container.build_id' => 'fe93718a',
    'container.build_time' => 1619102427,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDcoOOkQ');
