<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Panier extends \App\Entity\Panier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'prixTot', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'tvaTot', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'prixFinale', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'ListProduit'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'prixTot', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'tvaTot', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'prixFinale', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\Panier' . "\0" . 'ListProduit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Panier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTot(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTot', []);

        return parent::getPrixTot();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTot(?float $prixTot): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTot', [$prixTot]);

        return parent::setPrixTot($prixTot);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvaTot(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvaTot', []);

        return parent::getTvaTot();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvaTot(?float $tvaTot): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvaTot', [$tvaTot]);

        return parent::setTvaTot($tvaTot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixFinale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixFinale', []);

        return parent::getPrixFinale();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixFinale($prixFinale): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixFinale', [$prixFinale]);

        parent::setPrixFinale($prixFinale);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getParapharmacie(): ?\App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParapharmacie', []);

        return parent::getParapharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function setParapharmacie(?\App\Entity\Parapharmacie $parapharmacie): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParapharmacie', [$parapharmacie]);

        return parent::setParapharmacie($parapharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function getListProduit(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListProduit', []);

        return parent::getListProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function addListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListProduit', [$listProduit]);

        return parent::addListProduit($listProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\Panier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListProduit', [$listProduit]);

        return parent::removeListProduit($listProduit);
    }

}
