<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CategorieProduit extends \App\Entity\CategorieProduit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'imgCategorie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'lienImgCat', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'listProd'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'imgCategorie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'lienImgCat', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\CategorieProduit' . "\0" . 'listProd'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CategorieProduit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getParapharmacie(): ?\App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParapharmacie', []);

        return parent::getParapharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function setParapharmacie(?\App\Entity\Parapharmacie $parapharmacie): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParapharmacie', [$parapharmacie]);

        return parent::setParapharmacie($parapharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function addlistProd(\App\Entity\Produit $listProd): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addlistProd', [$listProd]);

        return parent::addlistProd($listProd);
    }

    /**
     * {@inheritDoc}
     */
    public function removelistProd(\App\Entity\Produit $listProd): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removelistProd', [$listProd]);

        return parent::removelistProd($listProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(string $categorie): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgCategorie', []);

        return parent::getImgCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgCategorie(?string $imgCategorie): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgCategorie', [$imgCategorie]);

        return parent::setImgCategorie($imgCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienImgCat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienImgCat', []);

        return parent::getLienImgCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienImgCat(?string $lienImgCat): \App\Entity\CategorieProduit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienImgCat', [$lienImgCat]);

        return parent::setLienImgCat($lienImgCat);
    }

}
