<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'login', '' . "\0" . 'App\\Entity\\User' . "\0" . 'mdp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adresseUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'specialite', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\User' . "\0" . 'role', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lienImageUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lienIconeUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'reclamations', '' . "\0" . 'App\\Entity\\User' . "\0" . 'actualites', '' . "\0" . 'App\\Entity\\User' . "\0" . 'reservations', '' . "\0" . 'App\\Entity\\User' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\User' . "\0" . 'listRendezvous', '' . "\0" . 'App\\Entity\\User' . "\0" . 'paniers', '' . "\0" . 'App\\Entity\\User' . "\0" . 'listProduit'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'login', '' . "\0" . 'App\\Entity\\User' . "\0" . 'mdp', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adresseUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'specialite', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\User' . "\0" . 'role', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lienImageUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lienIconeUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'reclamations', '' . "\0" . 'App\\Entity\\User' . "\0" . 'actualites', '' . "\0" . 'App\\Entity\\User' . "\0" . 'reservations', '' . "\0" . 'App\\Entity\\User' . "\0" . 'parapharmacie', '' . "\0" . 'App\\Entity\\User' . "\0" . 'listRendezvous', '' . "\0" . 'App\\Entity\\User' . "\0" . 'paniers', '' . "\0" . 'App\\Entity\\User' . "\0" . 'listProduit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin(string $login): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$login]);

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', []);

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp(string $mdp): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', [$mdp]);

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeFiscale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeFiscale', []);

        return parent::getMatriculeFiscale();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeFiscale(?string $matriculeFiscale): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeFiscale', [$matriculeFiscale]);

        return parent::setMatriculeFiscale($matriculeFiscale);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseUser', []);

        return parent::getAdresseUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseUser(string $adresseUser): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseUser', [$adresseUser]);

        return parent::setAdresseUser($adresseUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', []);

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(?string $specialite): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', [$specialite]);

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(int $role): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienImageUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienImageUser', []);

        return parent::getLienImageUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienImageUser(?string $lienImageUser): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienImageUser', [$lienImageUser]);

        return parent::setLienImageUser($lienImageUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienIconeUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienIconeUser', []);

        return parent::getLienIconeUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienIconeUser(?string $lienIconeUser): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienIconeUser', [$lienIconeUser]);

        return parent::setLienIconeUser($lienIconeUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getReclamations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReclamations', []);

        return parent::getReclamations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReclamation(\App\Entity\Reclamation $reclamation): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReclamation', [$reclamation]);

        return parent::addReclamation($reclamation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReclamation(\App\Entity\Reclamation $reclamation): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReclamation', [$reclamation]);

        return parent::removeReclamation($reclamation);
    }

    /**
     * {@inheritDoc}
     */
    public function getActualites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualites', []);

        return parent::getActualites();
    }

    /**
     * {@inheritDoc}
     */
    public function addActualite(\App\Entity\Actualite $actualite): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActualite', [$actualite]);

        return parent::addActualite($actualite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActualite(\App\Entity\Actualite $actualite): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActualite', [$actualite]);

        return parent::removeActualite($actualite);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\App\Entity\Reservation $reservation): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\App\Entity\Reservation $reservation): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getListRendezvous(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListRendezvous', []);

        return parent::getListRendezvous();
    }

    /**
     * {@inheritDoc}
     */
    public function addListRendezvou(\App\Entity\RendezVous $listRendezvou): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListRendezvou', [$listRendezvou]);

        return parent::addListRendezvou($listRendezvou);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListRendezvou(\App\Entity\RendezVous $listRendezvou): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListRendezvou', [$listRendezvou]);

        return parent::removeListRendezvou($listRendezvou);
    }

    /**
     * {@inheritDoc}
     */
    public function getParapharmacie(): ?\App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParapharmacie', []);

        return parent::getParapharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function setParapharmacie(?\App\Entity\Parapharmacie $Parapharmacie): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParapharmacie', [$Parapharmacie]);

        return parent::setParapharmacie($Parapharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaniers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaniers', []);

        return parent::getPaniers();
    }

    /**
     * {@inheritDoc}
     */
    public function addPanier(\App\Entity\Panier $panier): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPanier', [$panier]);

        return parent::addPanier($panier);
    }

    /**
     * {@inheritDoc}
     */
    public function removePanier(\App\Entity\Panier $panier): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePanier', [$panier]);

        return parent::removePanier($panier);
    }

    /**
     * {@inheritDoc}
     */
    public function getListProduit(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListProduit', []);

        return parent::getListProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function addListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListProduit', [$listProduit]);

        return parent::addListProduit($listProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListProduit', [$listProduit]);

        return parent::removeListProduit($listProduit);
    }

}
