<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parapharmacie extends \App\Entity\Parapharmacie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'nomPara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'adressePara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'telPara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'img_Para', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'lienImageP', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'region', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'categorieProduit', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'produits', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'paniers', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'listProduit', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'parapharmacien'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'nomPara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'adressePara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'telPara', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'img_Para', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'lienImageP', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'region', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'categorieProduit', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'produits', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'paniers', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'listProduit', '' . "\0" . 'App\\Entity\\Parapharmacie' . "\0" . 'parapharmacien'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parapharmacie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getcategorieProduit(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcategorieProduit', []);

        return parent::getcategorieProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function addcategorieProduit(\App\Entity\CategorieProduit $categorieProduit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addcategorieProduit', [$categorieProduit]);

        return parent::addcategorieProduit($categorieProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removecategorieProduit(\App\Entity\CategorieProduit $categorieProduit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removecategorieProduit', [$categorieProduit]);

        return parent::removecategorieProduit($categorieProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPara(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPara', []);

        return parent::getNomPara();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPara(string $nomPara): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPara', [$nomPara]);

        return parent::setNomPara($nomPara);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePara(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePara', []);

        return parent::getAdressePara();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePara(string $adressePara): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePara', [$adressePara]);

        return parent::setAdressePara($adressePara);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienImageP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienImageP', []);

        return parent::getLienImageP();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienImageP($lienImageP): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienImageP', [$lienImageP]);

        parent::setLienImageP($lienImageP);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelPara(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelPara', []);

        return parent::getTelPara();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelPara(string $telPara): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelPara', [$telPara]);

        return parent::setTelPara($telPara);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgPara()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgPara', []);

        return parent::getImgPara();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgPara($img_Para): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgPara', [$img_Para]);

        parent::setImgPara($img_Para);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduits', []);

        return parent::getProduits();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduit(\App\Entity\Produit $produit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduit', [$produit]);

        return parent::addProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduit(\App\Entity\Produit $produit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduit', [$produit]);

        return parent::removeProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion(): ?\App\Entity\Regions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(?\App\Entity\Regions $regions): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$regions]);

        return parent::setRegion($regions);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaniers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaniers', []);

        return parent::getPaniers();
    }

    /**
     * {@inheritDoc}
     */
    public function addPanier(\App\Entity\Panier $panier): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPanier', [$panier]);

        return parent::addPanier($panier);
    }

    /**
     * {@inheritDoc}
     */
    public function removePanier(\App\Entity\Panier $panier): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePanier', [$panier]);

        return parent::removePanier($panier);
    }

    /**
     * {@inheritDoc}
     */
    public function getListProduit(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListProduit', []);

        return parent::getListProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function addListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListProduit', [$listProduit]);

        return parent::addListProduit($listProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListProduit(\App\Entity\ListProduit $listProduit): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListProduit', [$listProduit]);

        return parent::removeListProduit($listProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getParapharmacien(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParapharmacien', []);

        return parent::getParapharmacien();
    }

    /**
     * {@inheritDoc}
     */
    public function addParapharmacien(\App\Entity\User $parapharmacien): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParapharmacien', [$parapharmacien]);

        return parent::addParapharmacien($parapharmacien);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParapharmacien(\App\Entity\User $parapharmacien): \App\Entity\Parapharmacie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParapharmacien', [$parapharmacien]);

        return parent::removeParapharmacien($parapharmacien);
    }

}
